default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  username: <%= ENV.fetch("PGUSER", "playtab") %>
  password: <%= ENV.fetch("PGPASSWORD", "playtab") %>
development:
  <<: *default
  database: playtab_development
test:
  <<: *default
  database: playtab_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
